name = '_Cruisers'

[matches]
classes=['Cruiser']

[topics]

[topics.overmatch_me]

[topics.winrate]
# What to show in the first line (as the primary information). Can be either "ship" or "name". Default is "name".
primary = "ship"
# Whether to hide the colored side bars indicating the ship class. 
# The side bars help in finding a particular ship more quickly, but hiding them makes a little bit more space 
# available for displaying the contents.
# Default is false.
#hideSidebars = true

[topics.pen_you]

[topics.torpedoes]
filter = { teams = [ "enemies" ] }

[topics.radar]
# The threshold in meters by which a ship's concealment may exceed its radar range 
# for it to still be considered to "almost" have a stealth radar capability.
# Default: 0; i.e. ships are never considered to "almost" have a stealth radar capability - they can either stealth
# radar or they can't.
almostThreshold = 500
